# Generated by Django 3.1 on 2020-08-27 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=25)),
                ('event_venue', models.CharField(max_length=25)),
                ('event_date', models.DateTimeField(default=None)),
                ('event_description', models.CharField(max_length=100)),
                ('event_link', models.URLField()),
                ('event_managers', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(default=models.CharField(max_length=15), max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Registration_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=25)),
                ('mobile', models.CharField(max_length=15)),
                ('payment_amount', models.CharField(max_length=5)),
                ('payment_ref', models.CharField(max_length=10)),
                ('extended_tour', models.CharField(max_length=3)),
                ('num_guests', models.IntegerField(default=1)),
                ('num_days', models.IntegerField(default=2)),
                ('mode_of_travel', models.CharField(max_length=5)),
                ('arrival_date', models.DateTimeField(default=None)),
                ('departure_date', models.DateTimeField(default=None)),
                ('pickup_reqd', models.CharField(max_length=5)),
                ('special_req', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='File_uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(default=None, upload_to='events')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
