# Generated by Django 3.1 on 2020-08-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_login_temp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_uploads',
            name='file_url',
            field=models.FileField(default=None, upload_to='media'),
        ),
    ]
