# Generated by Django 3.1 on 2020-08-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_uploads',
            name='file_url',
            field=models.FileField(default=None, upload_to='media/'),
        ),
    ]
