# Generated by Django 3.1 on 2020-08-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200829_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file_uploads',
            name='file_url',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
