# Generated by Django 3.1 on 2020-08-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200830_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='cancelled_date',
            field=models.DateTimeField(default=None),
        ),
    ]
